### ISSUE TITLE
How to inverse the goertzel DFT

### ISSUE THREAD

**Issue by fmbao** [chdh/dsp-collection-java#1]

**Comment by chdh** [comment]
The DFT with Goertzel produces the same result as the normal DFT or the FFT.
To reverse it, take the lower half of the result, normalize the amplitudes and synthesize with sine waves.
In [Dft.java](https://github.com/chdh/dsp-collection-java/blob/master/src/main/java/biz/source_code/dsp/transform/Dft.java), `synthesizeFromSpectrum()` is the inverse of `goertzelSpectrum()`.

**Comment by fmbao** [comment]
> The DFT with Goertzel produces the same result as the normal DFT or the FFT.
> To reverse it, take the lower half of the result, normalize the amplitudes and synthesize with sine waves.
> In [Dft.java](https://github.com/chdh/dsp-collection-java/blob/master/src/main/java/biz/source_code/dsp/transform/Dft.java), `synthesizeFromSpectrum()` is the inverse of `goertzelSpectrum()`.

 changed it,  according to your request, but did not get the corresponding result. Below is my code
```java

public static double[] synthesizeFromDft(Complex[] var0, boolean var1) {
        int var2 = var0.length * 2 - (var1 ? 1 : 2);
        double[] var3 = new double[var2];

        for(int var4 = 0; var4 < var0.length; ++var4) {
            Complex var5 = var0[var4];
            synthesizeSinusoidal(var3, var4, var5.abs() , var5.arg() );
        }

        return var3;
    }

    private static void synthesizeSinusoidal(double[] var0, int var1, double var2, double var4) {
        double var6 = 6.283185307179586D / (double)var0.length * (double)var1;

        for(int var8 = 0; var8 < var0.length; ++var8) {
            var0[var8] += var2/ (double)var0.length * Math.cos(var4 + var6 * (double)var8);
        }

    }

```
I'm sorry.I'm so stupid. Please teach me again. Thank you very much.
