### ISSUE TITLE
> The DFT with Goertzel produces the same result as the normal DFT or the FFT.

### ISSUE THREAD

**Issue by fmbao** [chdh/dsp-collection-java#2]
> The DFT with Goertzel produces the same result as the normal DFT or the FFT.
> To reverse it, take the lower half of the result, normalize the amplitudes and synthesize with sine waves.
> In [Dft.java](https://github.com/chdh/dsp-collection-java/blob/master/src/main/java/biz/source_code/dsp/transform/Dft.java), `synthesizeFromSpectrum()` is the inverse of `goertzelSpectrum()`.

 changed it,  according to your request, but did not get the corresponding result. Below is my code
```java

public static double[] synthesizeFromDft(Complex[] var0, boolean var1) {
        int var2 = var0.length * 2 - (var1 ? 1 : 2);
        double[] var3 = new double[var2];

        for(int var4 = 0; var4 < var0.length; ++var4) {
            Complex var5 = var0[var4];
            synthesizeSinusoidal(var3, var4, var5.abs() , var5.arg() );
        }

        return var3;
    }

    private static void synthesizeSinusoidal(double[] var0, int var1, double var2, double var4) {
        double var6 = 6.283185307179586D / (double)var0.length * (double)var1;

        for(int var8 = 0; var8 < var0.length; ++var8) {
            var0[var8] += var2/ (double)var0.length * Math.cos(var4 + var6 * (double)var8);
        }

    }

```
I'm sorry.I'm so stupid. Please teach me again. Thank you very much.

_Originally posted by @fmbao in https://github.com/chdh/dsp-collection-java/issues/1#issuecomment-782998092_

**Comment by fmbao** [comment]
The following code is my test code.

```java

double[] valueA = new double[4];
        valueA[0] = 1;
        valueA[1] = 2;
        valueA[2] = 3;
        valueA[3] = 4;

        Complex[] result3 = Dft.goertzel(valueA);  //   leave n/2 + 1

        Complex[] result2 = Dft.goertzelSpectrum(valueA);
        Complex[] result4 = new Complex[3];
        double[] a1 = new double[3];
        for (int i = 0; i < 3; i++) {
            result4[i] = result3[i];
        }

        double[] estimated_block_1 = synthesizeFromDft(result4,false);

```

**Comment by chdh** [comment]
```
   double[] a1 = new double[]{1, 2, 3, 4};
   Complex[] a2 = Dft.goertzelSpectrum(a1);
   double[] a3 = Dft.synthesizeFromSpectrum(a2, false);
   for (int i = 0; i < a3.length; i++) {
      System.out.println(a3[i]); }}
```

Don't decompile Java code. Use the [original source code](https://github.com/chdh/dsp-collection-java/blob/master/src/main/java/biz/source_code/dsp/transform/Dft.java) if you want to understand it.

There is also a test program [TestDft.java](https://github.com/chdh/dsp-collection-java/blob/master/src/test/java/TestDft.java) that you could study.

**Comment by fmbao** [comment]
> ```
>    double[] a1 = new double[]{1, 2, 3, 4};
>    Complex[] a2 = Dft.goertzelSpectrum(a1);
>    double[] a3 = Dft.synthesizeFromSpectrum(a2, false);
>    for (int i = 0; i < a3.length; i++) {
>       System.out.println(a3[i]); }}
> ```
> 
> Don't decompile Java code. Use the [original source code](https://github.com/chdh/dsp-collection-java/blob/master/src/main/java/biz/source_code/dsp/transform/Dft.java) if you want to understand it.
> 
> There is also a test program [TestDft.java](https://github.com/chdh/dsp-collection-java/blob/master/src/test/java/TestDft.java) that you could study.

OK ,Thank you!
